# Generated by Django 4.2.3 on 2023-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_leader_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='leader_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
