# Generated by Django 4.2.5 on 2023-10-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
